export type MenuItem = {
  children?: MenuItems
  soon?: boolean
  rootParentType?: ComponentType
}

type MenuItems = Partial<
  {
    [k in ComponentType]: MenuItem
  }
>

export const menuItems: MenuItems = {
  Accordion: {
    children: {
      Accordion: {},
      AccordionItem: {},
      AccordionButton: {},
      AccordionPanel: {},
      AccordionIcon: {},
    },
  },
  Alert: {
    children: {
      Alert: {},
      AlertDescription: {},
      AlertIcon: {},
      AlertTitle: {},
    },
  },
  AspectRatio: {},
  AvatarGroup: {
    rootParentType: 'Avatar',
  },
  Avatar: {},
  AvatarBadge: {
    rootParentType: 'Avatar',
  },
  Badge: {},
  Box: {},
  Breadcrumb: {
    children: {
      BreadcrumbItem: {},
      BreadcrumbLink: {},
    },
  },
  Button: {},
  Center: {},
  Container: {},
  Checkbox: {},
  CircularProgress: {},
  CloseButton: {},
  Code: {},
  Divider: {},
  Flex: {},
  FormControl: {
    children: {
      FormControl: {},
      FormLabel: {},
      FormHelperText: {},
      FormErrorMessage: {},
    },
  },
  Grid: {},
  Heading: {},
  Clock: {},
  WiFi: {},
  Highlight: {},
  Icon: {},
  IconButton: {},
  Image: {},
  Input: {},
  InputGroup: {
    rootParentType: 'Input',
    children: {
      InputGroup: {},
      Input: {},
      InputLeftAddon: {},
      InputRightAddon: {},
      InputRightElement: {},
      InputLeftElement: {},
    },
  },
  Link: {},
  List: {
    children: {
      List: {},
      ListItem: {},
    },
  },
  Kbd: {},
  NumberInput: {},
  Progress: {},
  Arc: {},
  Bar: {},
  Led: {},
  AnimImage: {},
  ButtonMatrix: {},
  Calendar: {},
  Canvas: {},
  Chart: {},
  ImageButton: {},
  Keyboard: {},
  Line: {},
  Lottie: {},
  Msgbox: {},
  ObjxTempl: {},
  Roller: {},
  Scale: {},
  Table: {},
  Tabview: {},
  Tileview: {},
  Radio: {},
  RadioGroup: {
    rootParentType: 'Radio',
  },
  SimpleGrid: {},
  Slider: {},
  Spinner: {},
  Select: {},
  Skeleton: {},
  SkeletonCircle: {},
  SkeletonText: {},
  Stack: {},
  Stat: {
    children: {
      StatGroup: {},
      Stat: {},
      StatLabel: {},
      StatNumber: {},
      StatHelpText: {},
      StatArrow: {},
    },
  },
  Switch: {},
  Tabs: {
    children: {
      Tabs: {},
      Tab: {},
      TabList: {},
      TabPanel: {},
      TabPanels: {},
    },
  },
  Tag: {},
  Text: {},
  Textarea: {},
  Menu: { soon: true },
}

export const componentsList: ComponentType[] = [
  'Accordion',
'AccordionIcon',
'AccordionItem',
'AccordionPanel',
'Alert',
'AlertDescription',
'AlertIcon',
'AlertTitle',
'AnimImage',
'Arc',
'AspectRatio',
'Avatar',
'AvatarBadge',
'AvatarGroup',
'Badge',
'Bar',
'Box',
'Breadcrumb',
'BreadcrumbItem',
'BreadcrumbLink',
'Button',
'ButtonMatrix',
'Calendar',
'Canvas',
'Center',
'Chart',
'Checkbox',
'CircularProgress',
'CloseButton',
'Code',
'Container',
'Divider',
'Editable',
'Flex',
'FormControl',
'FormErrorMessage',
'FormHelperText',
'FormLabel',
'Grid',
'Heading',
'Clock',
'WiFi',
'Highlight',
'Icon',
'IconButton',
'Image',
'ImageButton',
'Input',
'InputGroup',
'InputLeftAddon',
'InputLeftElement',
'InputRightAddon',
'InputRightElement',
'Kbd',
'Keyboard',
'Led',
'Line',
'Link',
'List',
'ListIcon',
'ListItem',
'Lottie',
'Menu',
'Msgbox',
'NumberInput',
'ObjxTempl',
'Progress',
'Radio',
'RadioGroup',
'Roller',
'Scale',
'Select',
'Slider',
'SimpleGrid',
'Spinner',
'Skeleton',
'SkeletonCircle',
'SkeletonText',
'Stack',
'Stat',
'StatArrow',
'StatGroup',
'StatHelpText',
'StatLabel',
'StatNumber',
'Switch',
'Tab',
'Table',
'TabList',
'TabPanel',
'TabPanels',
'Tabs',
'Tabview',
'Tag',
'Text',
'Textarea',
'Tileview',
]

export const aiSupportedComponents: ComponentType[] = componentsList.filter(
  (type) =>
    ![
      'Accordion',
      'AccordionIcon',
      'AccordionItem',
      'AccordionPanel',
      'Alert',
      'AlertDescription',
      'AlertIcon',
      'AlertTitle',
      'AnimImage',
      'AspectRatio',
      'Avatar',
      'AvatarBadge',
      'AvatarGroup',
      'Badge',
      'Breadcrumb',
      'BreadcrumbItem',
      'BreadcrumbLink',
      'Center',
      'CloseButton',
      'Code',
      'Container',
      'Divider',
      'Editable',
      'Flex',
      'FormControl',
      'FormErrorMessage',
      'FormHelperText',
      'FormLabel',
      'Grid',
      'Highlight',
      'ImageButton',
      'InputGroup',
      'InputLeftAddon',
      'InputLeftElement',
      'InputRightAddon',
      'InputRightElement',
      'Kbd',
      'Link',
      'List',
      'ListIcon',
      'ListItem',
      'Lottie',
      'Menu',
      'NumberInput',
      'ObjxTempl',
      'Radio',
      'RadioGroup',
      'SimpleGrid',
      'Spinner',
      'Skeleton',
      'SkeletonCircle',
      'SkeletonText',
      'Stack',
      'Stat',
      'StatArrow',
      'StatGroup',
      'StatHelpText',
      'StatLabel',
      'StatNumber',
      'Tab',
      'TabList',
      'TabPanel',
      'TabPanels',
      'Tabs',
      'Tag',
    ].includes(type)
)